TextMessagingService/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TextMessagingService.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }

        public DbSet<Login> Login { get; set; }
    }
}

TextMessagingService/Models/ErrorViewModel.cs
using System;

namespace TextMessagingService.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TextMessagingService/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TextMessagingService.Models
{
    public class Login
    {
        [Key]
        public int U_id { get; set; }

        public string U_name { get; set; }
        [Required]

        public string U_pw { get; set; }
        [Required]

        public int U_pn { get; set; }


    }
}

TextMessagingService/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TextMessagingService.Models;

namespace TextMessagingService.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TextMessagingService/Controllers/LandingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TextMessagingService.Models;

namespace TextMessagingService.Controllers
{
    [Route("api/Login")]
    [ApiController]
    public class LandingController : Controller
    {

        private readonly ApplicationDbContext _db;

        
        public LandingController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Login.ToListAsync() });
        }



        [HttpDelete]
        public async Task<IActionResult> Delete(int U_id)
        {
            var bookFromDb = await _db.Login.FirstOrDefaultAsync(u => u.U_id == U_id);

            if (bookFromDb == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }

            _db.Login.Remove(bookFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Delete successful" });
        }
        
    }
}

TextMessagingService/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


<body>
    <div class="container-fluid padding">
        <div class="padding">

            <a href="https://localhost:44352/Home/Login">Visit the login page</a>

        </div>
    </div>

            

           




</body>

TextMessagingService/Views/Home/Login.cshtml
@{
    ViewData["Title"] = "Login Page";
}
<h1>@ViewData["Title"]</h1>

<body>


    <form action="https://localhost:44352/Home/Privacy" method="post">

        <div class="container-fluid padding">
            <div class="padding">
                <label for="uname"><b>Username</b></label>
                <input type="text" placeholder="Enter Username" name="uname" required>

                <label for="psw"><b>Password</b></label>
                <input type="password" placeholder="Enter Password" name="psw" required>

                <!--FIXME: Still need a landing page after logging in
                Currently just goes to the index/home page-->
                <button type="submit" asp-area="" asp-controller="Home" asp-action="Index">Login</button>

                <label>
                    <input type="checkbox" checked="checked" name="remember"> Remember me
                </label>


                <label for="userphonenum">
                    <b>
                        Please Enter your phone number to receive updates.
                    </b>
                    <input type="tel" placeholder="Enter your phone number" name="u_pnum" required />
                </label>
            </div>
        </div>



        <div class="container-fluid" style="background-color:#f1f1f1">
            <button type="button" class="cancelbtn">Cancel</button>
            <span class="psw">Forgot <a href="#">password?</a></span>
        </div>
    </form>

    
     <!--

    <button onclick="Landing/Index" asp-area="" asp-controller="Landing" asp-action="Index">Login</button>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Landing" asp-action="Index">landing Login</a>
    </li>

            -->
</body>

TextMessagingService/Views/Landing/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Twilio";
}
<h1>@ViewData["Title"]</h1>

<p>Twilio functionality: .</p>

TextMessagingService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TextMessagingService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TextMessagingService</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Acct Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TextMessagingService - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>